# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 5
  - package-ecosystem: 'npm'
    directory: '/www'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 15
  - package-ecosystem: 'npm'
    directory: '/react-hooks'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 15
